
# Create the instance (containers) of the images/
services:
    mariadb:
        build: 
            context: ./srcs/requirements/mariadb
            dockerfile: Dockerfile
        ports:
            - "3306:3306"
        networks:
            - inception-network
        restart: always
        volumes:
            - db:/var/lib/mysql
        env_file: .env
    
    wordpress:
        build: 
            context: ./srcs/requirements/wordpress
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        networks:
            - inception-network
        restart: always
        depends_on:
            - mariadb
        volumes:
            - wordpress_volume:/var/www/html
        env_file: .env
    nginx:
        build: 
            context: ./srcs/requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        networks:
            - inception-network
        restart: unless-stopped
        depends_on:
            - wordpress
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}

networks:
    inception-network:
        driver: bridge

# Create the volume
volumes:
    db:
        driver: local
        driver_opts:
            type: none
            device: /home/ifounas/data/mariadb
            o: bind
    wordpress_volume:
        driver: local
        driver_opts:
            type: none
            device: /home/ifounas/data/wordpress
            o: bind